### ISSUE TITLE
No padding between css variables and other properties

### ISSUE THREAD

**Issue by nikkeyl** [archoleat/stylelint-config-extended-scss#176]
### What Steps are Needed to Reproduce the Bug?

1. Remove an empty line between a variable and a property
1. Run Stylelint

### What Did You Expect to Happen?

Before Stylelint:

```scss
.class {
  --variable: 0;
  color: #fff;
}
```

After Stylelint:

```scss
.class {
  --variable: 0;

  color: #fff;
}
```

### What Actually Happened?

Before Stylelint:

```scss
.class {
  --variable: 0;
  color: #fff;
}
```

After Stylelint:

```scss
.class {
  --variable: 0;
  color: #fff;
}
```

### Code of Conduct

- [X] I Agree to Follow This Project's Code of Conduct
