### ISSUE TITLE
Stylelint needs to be run twice for the properties to be properly sorted

### ISSUE THREAD

**Issue by nikkeyl** [Archoleat/stylelint-config-extended-scss#77]
### What Steps are Needed to Reproduce the Bug?

1. Shuffle selectors and properties.
2. Run Stylelint with Archoleat config.

### What Did You Expect to Happen?

Before lint:
```scss
.popup {
  &--show {
    pointer-events: auto;

    opacity: 1;

    overflow-block: auto;
.lock & {
      opacity: 1;
    }
    overscroll-behavior-block: none;

    scrollbar-gutter: stable;

    .popup__content {
      opacity: 1;

      scale: 1;
    }
  }
}
```

After lint:
```scss
.popup {
  &--show {
    pointer-events: auto;

    opacity: 1;

    overflow-block: auto;

    overscroll-behavior-block: none;

    scrollbar-gutter: stable;

    .popup__content {
      opacity: 1;

      scale: 1;
    }

    .lock & {
      opacity: 1;
    }
  }
}
```

### What Actually Happened?

Before lint:
```scss
.popup {
  &--show {
    pointer-events: auto;

    opacity: 1;

    overflow-block: auto;
.lock & {
      opacity: 1;
    }
    overscroll-behavior-block: none;

    scrollbar-gutter: stable;

    .popup__content {
      opacity: 1;

      scale: 1;
    }
  }
}
```

After lint:
```scss
.popup {
  &--show {
    pointer-events: auto;

    opacity: 1;

    overflow-block: auto;
    .lock & {
      opacity: 1;
    }
    overscroll-behavior-block: none;

    scrollbar-gutter: stable;

    .popup__content {
      opacity: 1;

      scale: 1;
    }
  }
}
```

### Code of Conduct

- [X] I Agree to Follow This Project's Code of Conduct
